# Generated by Django 3.0.4 on 2020-05-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pub_date'], 'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
    ]
