# Generated by Django 3.0.4 on 2020-10-11 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forestry', '0004_comment_commentreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='full_name',
        ),
        migrations.AddField(
            model_name='commentreply',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='message',
            field=models.TextField(verbose_name='Reply'),
        ),
    ]
