# Generated by Django 3.0.4 on 2022-04-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0006_auto_20220411_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='author biography'),
        ),
        migrations.AddField(
            model_name='author',
            name='bio_rw',
            field=models.TextField(blank=True, null=True, verbose_name='author biography'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_rw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
