# Generated by Django 3.0.4 on 2020-05-05 07:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200505_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesofseed',
            name='overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='overview'),
        ),
    ]
