# Generated by Django 3.0.4 on 2020-05-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_typesofseed_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedproduct',
            name='pre_treatment',
        ),
        migrations.AddField(
            model_name='seedproduct',
            name='pre_treatment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.SeedPretreatment'),
        ),
    ]
