# Generated by Django 3.0.4 on 2020-05-05 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200505_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedproduct',
            name='seed_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.TypesOfSeed'),
        ),
    ]
