# Generated by Django 3.0.4 on 2020-05-05 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200505_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedproduct',
            name='pre_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.SeedPretreatment'),
        ),
        migrations.AlterField(
            model_name='seedproduct',
            name='seed_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.TypesOfSeed'),
        ),
    ]
