# Generated by Django 3.0.4 on 2020-05-10 14:53

from django.db import migrations, models
import store.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200505_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedproduct',
            name='image1',
            field=models.ImageField(blank=True, default='default/product_image1.jpg', null=True, upload_to=store.utils.photo_path, verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='seedproduct',
            name='image2',
            field=models.ImageField(blank=True, default='default/product_image2.jpg', null=True, upload_to=store.utils.photo_path, verbose_name='image2'),
        ),
    ]
