# Generated by Django 3.0.4 on 2020-07-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forestry', '0002_auto_20200510_1142'),
        ('store', '0007_auto_20200510_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedproduct',
            name='related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forestry.BlogPost'),
        ),
    ]
