[tool.poetry]
name = "igiti"
version = "0.1.0"
description = "The project to manage the tree related information"
authors = ["Fabrice Hafashimana <tumbafabruce@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
autoflake = "1.4"
autopep8 = "1.6.0"
boto3 = "1.23.5"
brotli = "1.0.9"
chardet = "5.0.0"
cloudinary = "1.30.0"
cssselect = "1.2.0"
django-ajax = "0.3.0"
django-allauth = "0.50.0"
django-autoslug = "1.9.8"
django-backupdb = "0.7.0"
django-ckeditor = "6.4.1"
django-countries = "7.3.2"
django-heroku = "0.3.1"
django-hitcount = "1.3.5"
django-imagekit = "4.1.0"
django-modeltranslation = "0.18.2"
django-storages = "1.12.3"
django-widget-tweaks = "1.4.12"
djangorestframework = "3.13.1"
lockfile = "0.12.2"
pip = "22.3.1"
pipdeptree = "2.3.3"
pydyf = "0.5.0"
pypdf = "1.13"
pyphen = "0.13.2"
python-decouple = "3.6"
setuptools = "58.1.0"
social-auth-app-django = "5.0.0"
stripe = "3.1.0"
tinycss = "0.4"
unidecode = "1.3.4"
xhtml2pdf = "0.2.8"
zopfli = "0.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

